name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Önce dosyayı bulalım ve izin verelim
      - name: Make Gradlew Executable
        run: |
          find . -name "gradlew" -exec chmod +x {} +

      # APK Üretme (Dosyayı bulduğu yerde çalıştırır)
      - name: Build with Gradle
        run: |
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "HATA: gradlew dosyası bulunamadı!"
            exit 1
          fi
          cd $(dirname $GRADLEW_PATH)
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WeatherTracker-APK
          path: "**/*.apk"
